# Generated by Django 4.2.2 on 2023-06-15 03:36

from django.db import migrations
import users.user_manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.user_manager.UserManager()),
            ],
        ),
    ]
