# Generated by Django 4.2.2 on 2023-06-15 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('audio_file', models.FileField(help_text='Upload audio file', upload_to='audiofiles/')),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('protected', 'Protected')], default='public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, default=None, related_name='sharedwith', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
